# Generated by Django 5.1 on 2024-08-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=100)),
                ('order_name', models.CharField(max_length=255)),
                ('order_loinc_code', models.CharField(max_length=100)),
                ('loinc_name', models.CharField(max_length=255)),
                ('order_loinc_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderingPhysicianNPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SourceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_source', models.CharField(max_length=255)),
                ('source_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimen_sources', to='myapp.sourcedescription')),
            ],
        ),
        migrations.CreateModel(
            name='SourceSNOMEDCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_snomed_code', models.CharField(max_length=100)),
                ('specimen_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snomed_codes', to='myapp.specimensource')),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_type', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimen_types', to='myapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenTypeSNOMEDCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_type_snomed_code', models.CharField(max_length=100)),
                ('specimen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snomed_codes', to='myapp.specimentype')),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.order')),
                ('source_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.sourcedescription')),
                ('source_snomed_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.sourcesnomedcode')),
                ('specimen_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.specimensource')),
                ('specimen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.specimentype')),
                ('specimen_type_snomed_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.specimentypesnomedcode')),
            ],
        ),
        migrations.AddField(
            model_name='sourcedescription',
            name='specimen_type_snomed_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_descriptions', to='myapp.specimentypesnomedcode'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=255)),
                ('patient_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('entry_number', models.CharField(max_length=100)),
                ('extract_flag', models.BooleanField(default=False)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.city')),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.environment')),
                ('ethnicity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.ethnicity')),
                ('patient_gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.gender')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.race')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='TestLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_locations', to='myapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_code', models.CharField(max_length=100, unique=True)),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitters', to='myapp.district')),
                ('ordering_physician_npi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitters', to='myapp.orderingphysiciannpi')),
                ('test_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitters', to='myapp.testlocation')),
            ],
        ),
        migrations.AddField(
            model_name='orderingphysiciannpi',
            name='test_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_physicians', to='myapp.testlocation'),
        ),
    ]
