# Generated by Django 5.1 on 2024-08-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=100)),
                ('order_name', models.CharField(max_length=255)),
                ('order_loinc_code', models.CharField(max_length=100)),
                ('loinc_name', models.CharField(max_length=255)),
                ('order_loinc_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=255)),
                ('patient_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_last_name', models.CharField(max_length=255)),
                ('patient_gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('race', models.CharField(max_length=50)),
                ('ethnicity', models.CharField(max_length=50)),
                ('entry_number', models.CharField(max_length=100)),
                ('env', models.CharField(max_length=50)),
                ('extract_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SourceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_code', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=255)),
                ('orderingphysiciannpi', models.CharField(max_length=100)),
                ('collectiondate', models.DateField()),
                ('collectiontime', models.TimeField()),
                ('testlocation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_source', models.CharField(max_length=255)),
                ('source_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimen_sources', to='myapp.sourcedescription')),
            ],
        ),
        migrations.CreateModel(
            name='SourceSNOMEDCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_snomed_code', models.CharField(max_length=100)),
                ('specimen_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snomed_codes', to='myapp.specimensource')),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_type', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimen_types', to='myapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenTypeSNOMEDCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_type_snomed_code', models.CharField(max_length=100)),
                ('specimen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snomed_codes', to='myapp.specimentype')),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.order')),
                ('source_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.sourcedescription')),
                ('source_snomed_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.sourcesnomedcode')),
                ('specimen_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.specimensource')),
                ('specimen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.specimentype')),
                ('specimen_type_snomed_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='myapp.specimentypesnomedcode')),
            ],
        ),
        migrations.AddField(
            model_name='sourcedescription',
            name='specimen_type_snomed_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_descriptions', to='myapp.specimentypesnomedcode'),
        ),
    ]
